baseURL = 'https://kennypeng15.github.io/'
languageCode = 'en-us'
title = ""
theme = 'hugo-theme-relearn'

[outputs]
home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]
section = ["HTML", "RSS"]
page = ["HTML", "RSS"]

[params]
author.name = "Kenny Peng"
description = "Kenny Peng's Personal Site"
themeVariant = [
  { identifier = "custom-dark", name = "Dark"  },
  { identifier = "custom-light",  name = "Light"}
]
